version: '2.2'
services:
  postgres-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: shopping-cart
      POSTGRES_PASSWORD: shopping-cart

  # this second PostgresSQL is used when running test
  postgres-db-test:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: shopping-cart
      POSTGRES_USER: shopping-cart
      POSTGRES_PASSWORD: shopping-cart

# See dockerhub for different versions of kafka and zookeeper
# https://hub.docker.com/r/wurstmeister/kafka/
# https://hub.docker.com/r/wurstmeister/zookeeper/
  zookeeper:
    image: ubuntu/zookeeper:edge
    container_name: ubuntu-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  
  kafka:
    image: ubuntu/kafka:3.1-22.04_beta
    container_name: ubuntu-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  kafka-consumer:
    image: ubuntu/kafka:3.1-22.04_beta
    command: bash -c "mkdir -vp /tmp/kafka-logs && /opt/kafka_2.13-2.7.0/bin/kafk-console-consumer.sh --zookeeper zookeeper:2181 --from-beginning --topic-name > /tmp/kafka-logs/topic-name.log"
    ports:
      - "9094:9092"
    links:
      - zookeeper
      - kafka
    volumes:
      - ./kafka-1-logs:/tmp/kafka-logs

  wait-for-kafka:
    image: waisbrot/wait
    links:
      - kafka
    environment:
      - TARGETS=kafka:9092
