version: '2.4'
services:
  postgres-db:
    # uncomment when using apple silicon
    platform: linux/arm64/v8
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: shopping-cart
      POSTGRES_PASSWORD: shopping-cart

  # this second PostgresSQL is used when running test
  postgres-db-test:
    # uncomment when using apple silicon
    platform: linux/arm64/v8
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: shopping-cart
      POSTGRES_USER: shopping-cart
      POSTGRES_PASSWORD: shopping-cart

  zookeeper:
    # uncomment when using apple silicon
    platform: linux/arm64/v8
    image: ubuntu/zookeeper
    ports:
      - "2181:2181"

  kafka:
    # uncomment when using apple silicon
    platform: linux/arm64/v8
    image: ubuntu/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  kafka-consumer:
    # uncomment when using apple silicon
    platform: linux/arm64/v8
    image: ubuntu/kafka
    command: bash -c "mkdir -vp /tmp/kafka-logs && /opt/kafka/bin/kafka-console-consumer.sh --zookeeper zookeeper:2181 --from-beginning --topic-name > /tmp/kafka-logs/topic-name.log"
    ports:
      - "9094:9092"
    links:
      - zookeeper
      - kafka
    volumes:
      - ./kafka-1-logs:/tmp/kafka-logs

  wait-for-kafka:
    image: waisbrot/wait
    links:
      - kafka
    environment:
      - TARGETS=kafka:9092
